
@baseUrl = https://8080-lucastamaga-atividadesp-bht0calsqgc.ws-us116.gitpod.io

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBUEkgSm9nb3MiLCJzdWIiOiJ1c2VyIiwiZXhwIjoxNzI2MDA1MDI5fQ.lPJasbcXb88b1lr3BVZ_Rx5ms_s_iF1oFGF7rwRIjL8
###


GET {{baseUrl}}/filmes
Content-Type: application/json
Authorization: Bearer {{token}}

###

POST {{baseUrl}}/filmes
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nomeFilme": "Titanic",
    "genero": "Drama"
}

###

GET {{baseUrl}}/filmes/1
Authorization: Bearer {{token}}


###

PUT {{baseUrl}}/filmes/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nomeFilme": "Avatar",
    "genero": "Aventura"
}


###
DELETE {{baseUrl}}/filmes/2
Authorization: Bearer {{token}}